[project]
name = "norsklang_app"
version = "0.1.0"
entry = "app.no"

[paths]
source = "."
stdlib = "std"
build = "build"

[registry]
sources = ["packages/remote_registry_example.json"]

[dependencies]
butikk = "./packages/butikk"
[security]
trusted_git_hosts = ["github.com", "*.github.com"]
trusted_url_hosts = ["example.com"]
trusted_registry_sha256 = "7e706e304b32876ef6c4fc58f187039313676e8ae3a20d7a12466249dfc95fab"
